<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<c:url value="/basic" var="basic" />
<c:url value="/advanced" var="advanced" />
<c:url value="/ajax" var="ajax" />
<c:url value="/themes" var="themes" />
<c:url value="/features" var="features" />
<c:url value="/plugins" var="plugins" />

<div class="row-fluid">
   <div class="span5 offset3">
      <a href="http://datatables.net/"> <img src="<c:url value="/img/logo_DataTables4j.png" />" style="float: left; margin-right: 20px;" />
      </a>
      <h2>DataTables4j Live Demo</h2>
      <hr />
   </div>
</div>

<div class="row-fluid marketing">
   <div class="span5 offset1">
      <h3>
         <i class="icon-leaf"></i> Basic examples
      </h3>
      <p>All basic examples : sorting, filtering, paging, how to use implicit objects, CDN option and others !</p>
      <p>
         <a class="btn" href="${basic}/home">View details »</a>
      </p>
   </div>
   <div class="span5">
      <h3>
         <i class="icon-certificate"></i> Advanced examples
      </h3>
      <p>See how to override the default configuration, how to use DataTables plugins, how to internationalize the table and others !</p>
      <p>
         <a class="btn" href="${advanced}/home">View details »</a>
      </p>
   </div>
</div>

<div class="row-fluid">
   <div class="span5 offset1">
      <h3>
         <i class="icon-th-large"></i> Features
      </h3>
      <p>Export in PDF, CSV, XLS and others formats or how to enable web resources aggregation and compression !</p>
      <p>
         <a class="btn" href="${features}/home">View details »</a>
      </p>
   </div>
   <div class="span5">
      <h3>
         <i class="icon-refresh"></i> AJAX examples
      </h3>
      <p>For AJAX sources and server-side processing, it's right here !</p>
      <p>
         <a class="btn" href="${ajax}/home">View details »</a>
      </p>
   </div>
</div>

<div class="row-fluid">
   <div class="span5 offset1">
      <h3>
         <i class="icon-plus"></i> Plugins
      </h3>
      <p>Need to use a DataTables plugin ? See how easy it is !
      <p>
         <a class="btn" href="${plugins}/home">View details »</a>
      </p>
   </div>
   <div class="span5">
      <h3>
         <i class="icon-magic"></i> Themes
      </h3>
      <p>See how to easily prettify your tables using embedded themes and others cool stuff !</p>
      <p>
         <a class="btn" href="${themes}/home">View details »</a>
      </p>
   </div>
</div>

<div class="row-fluid">
   <div class="span7 offset3">
      <p>
         <br /> <i class="icon-info-sign icon-large"></i> You are advised to use browser development tools like <a href="http://getfirebug.com/">Firebug</a>
         or <a href="http://developer.chrome.com/extensions/tut_debugging.html">built-in ones</a> to see the web resources generated by <strong>Datatables4j</strong>.
      </p>
   </div>
</div>
