INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (1,'Warwick','73302');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (2,'Bodmin','E2J 6Y0');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (3,'Ribnitz-Damgarten','42641');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (4,'Gallicchio','EO9X 2DK');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (5,'Qualicum Beach','3961');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (6,'Bovesse','03300');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (7,'Macklin','56015');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (8,'Napier','68978');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (9,'Tuglie','30833');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (10,'Villers-aux-Tours','1693');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (11,'Cimolais','A8P 8Z8');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (12,'Paglieta','41485');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (13,'Hallein','5620');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (14,'A Coruña','64154');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (15,'Annapolis','8567');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (16,'Kessel','DD9C 7WG');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (17,'Saint-Die-des-Vosges','6378');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (18,'Newtonmore','6120');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (19,'San Felice a Cancello','G8V 7G3');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (20,'Rockville','54693');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (21,'Avennes','32741');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (22,'Racine','S9 2RP');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (23,'Giugliano in Campania','5485');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (24,'Bon Accord','95085');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (25,'Villers-la-Ville','43838');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (26,'Lasne','74603-035');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (27,'Curon Venosta/Graun im Vinschgau','10815');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (28,'Breton','76854');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (29,'Bellevue','2238');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (30,'Orbais','G4H 6R5');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (31,'Chestermere','65234');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (32,'Nobressart','06553');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (33,'Seloignes','06734');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (34,'Berwick-upon-Tweed','6410');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (35,'Rouvroy','9108');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (36,'Birmingham','8711');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (37,'Castelbianco','1688ZM');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (38,'Monticelli d Ongina','70680');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (39,'Bad Neuenahr-Ahrweiler','60728');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (40,'Rapone','73078');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (41,'Siddi','07559');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (42,'Hamilton','Y6C 6P5');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (43,'Cimitile','ID3T 8RC');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (44,'Sauveniere','4578');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (45,'Santa Caterina Villarmosa','70514-366');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (46,'Herdersem','21048');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (47,'Southaven','K2F 2MO');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (48,'Swindon','67311');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (49,'Ville de Maniwaki','74395-017');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (50,'Nashville','53528');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (51,'Pietrasanta','LO9D 5NQ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (52,'Fuenlabrada','02814');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (53,'Bregenz','83781');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (54,'San Vito Chietino','92595');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (55,'Serralunga d Alba','6823');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (56,'Ambresin','L4Y 0V6');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (57,'Clare','61400');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (58,'Orange','T9L 2B9');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (59,'Wolfurt','65523');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (60,'Gargazzone/Gargazon','68469');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (61,'Shepparton','5526CL');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (62,'Gonnosnò','67025');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (63,'Fermont','3261');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (64,'Comano','75647');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (65,'Torgny','8308');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (66,'Wierde','9456');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (67,'San Giacomo degli Schiavoni','0893IF');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (68,'Governador Valadares','19003');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (69,'Travo','4110');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (70,'Jasper','34429');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (71,'Nalinnes','10909');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (72,'Northampton','94442');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (73,'Marseille','54250');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (74,'Largs','4972');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (75,'Halifax','60019');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (76,'Norman Wells','26708');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (77,'Anderlues','57994');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (78,'Enns','65820');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (79,'Boneffe','4746');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (80,'Strausberg','36921');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (81,'Rocca d Arazzo','EO3 3JJ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (82,'Evesham','71905');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (83,'Hudson s Hope','56513');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (84,'Nordhorn','9494');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (85,'Vichte','21556-624');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (86,'Cimitile','6681');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (87,'Southwell','11292');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (88,'Ham-sur-Sambre','84815');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (89,'Sassocorvaro','J0S 6SE');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (90,'Ostra Vetere','21203');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (91,'Codognè','6924');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (92,'West Ham','51119');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (93,'Viddalba','93848');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (94,'Vernon','1855MW');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (95,'Biercoe','77819-953');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (96,'Radebeul','9683');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (97,'Orroli','27504-093');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (98,'Oss','28557');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (99,'Glendale','35797');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (100,'Caprino Bergamasco','8207');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (101,'Koningshooikt','3154');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (102,'Riviere-du-Loup','0479FR');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (103,'Aylesbury','41172-887');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (104,'Avennes','06412');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (105,'Naperville','46386');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (106,'Hall in Tirol','61214');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (107,'Shawville','39481');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (108,'Batiscan','X1M 5T4');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (109,'Cuccaro Vetere','8632');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (110,'Desamparados','A2Z 1K0');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (111,'Harrisburg','71400');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (112,'Götzis','84112');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (113,'Wuppertal','QD3O 2IP');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (114,'Ravels','9653');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (115,'Hofheim am Taunus','78116-167');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (116,'Canino','40468');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (117,'Montreuil','1834JN');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (118,'Spruce Grove','12390');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (119,'Whitchurch-Stouffville','5718');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (120,'Colorado Springs','73934');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (121,'Kilmalcolm','29134');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (122,'Radicofani','6560FL');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (123,'Wanganui','8517');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (124,'Castiglione di Garfagnana','5458QE');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (125,'Ingolstadt','9529');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (126,'Hulst','E4J 0A4');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (127,'Oyen','75719');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (128,'Kilmarnock','11407');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (129,'Zutendaal','46330');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (130,'Orp-le-Grand','78546');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (131,'Hengelo','18651');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (132,'Ollolai','M3B 0K1');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (133,'Salzgitter','51209');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (134,'Georgia','7332');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (135,'Guildford','61763');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (136,'Huntly','90481');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (137,'Ávila','71565');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (138,'Chaudfontaine','4499');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (139,'Wels','9231');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (140,'Ferrandina','95279-775');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (141,'Arbroath','40315');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (142,'Gaggio Montano','11268');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (143,'Versailles','J6 2BT');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (144,'Cervinara','16871');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (145,'Breton','3153');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (146,'Torrevieja','96759');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (147,'Recanati','87205');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (148,'Ulm','9924');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (149,'Montreuil','6577');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (150,'Warspite','8432');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (151,'Swan Hills','89301-332');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (152,'Cantalupo in Sabina','9185');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (153,'Salvador','31617');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (154,'Sluis','21853');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (155,'Chiaromonte','36067');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (156,'Nakusp','1643');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (157,'Shepparton','9499TU');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (158,'Sant Angelo a Fasanella','7776LS');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (159,'Aklavik','94491');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (160,'Bromley','19650');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (161,'Crieff','15272');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (162,'Las Vegas','02149');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (163,'Ambresin','Y4V 8S7');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (164,'Zeitz','KD1 4MA');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (165,'Tongue','45292');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (166,'Evere','8985GP');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (167,'Mundare','35731');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (168,'Hastings','47010');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (169,'Verrebroek','2205');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (170,'Grand-Rosiere-Hottomont','1844');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (171,'Flint','BD05 8UU');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (172,'Huntley','91895');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (173,'Ledeberg','10802');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (174,'Cornwall','8035');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (175,'Ottignies-Louvain-la-Neuve','24972-791');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (176,'Saint-Medard-en-Jalles','1224');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (177,'Dreieich','OC8 5AG');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (178,'Castel di Tora','13260-845');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (179,'Marneffe','4778');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (180,'Wandlitz','H85 3AS');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (181,'Corte Brugnatella','V1H 5E6');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (182,'Glain','3764');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (183,'San Lazzaro di Savena','11815');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (184,'Gap','30718');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (185,'Westerlo','89616');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (186,'Caplan','11315');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (187,'Lamorteau','69691');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (188,'Fairbanks','20314');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (189,'Essex','3263');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (190,'Etobicoke','NI6I 7ES');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (191,'Mont','92536');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (192,'Grasse','VG4O 0YA');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (193,'Delft','33643');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (194,'Itajaí','3841');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (195,'Hartlepool','41318');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (196,'Alkmaar','28966');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (197,'Thionville','SU10 1MV');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (198,'Knokke','16002');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (199,'Saguenay','3375');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (200,'Melton Mowbray','15985');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (201,'Heilbronn','O64 5WE');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (202,'Pietrarubbia','7362');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (203,'Sorradile','74764-383');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (204,'Nocciano','18291');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (205,'Burlington','64628');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (206,'Castor','61213');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (207,'Hastings','4106KM');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (208,'Beverlo','6061RZ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (209,'Rotorua','0452VX');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (210,'Kenosha','G1Z 3H7');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (211,'Fusignano','4432ZP');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (212,'Bleid','57924-381');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (213,'Lillois-Witterzee','2562');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (214,'Taunton','35241');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (215,'Coalhurst','MB4 3WX');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (216,'Guardia Perticara','68630');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (217,'Wodonga','L5B 8X4');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (218,'Shawville','71524');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (219,'Turriaco','72080-370');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (220,'Tours','2174');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (221,'Ruthin','89011');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (222,'Sesto al Reghena','2589');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (223,'Melbourne','9547');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (224,'Tay','67896-787');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (225,'Genval','71254');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (226,'Santa Cruz de Tenerife','34388');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (227,'Hope','YP5 9ZE');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (228,'Cabras','4546');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (229,'Oklahoma City','3658');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (230,'Westende','8936');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (231,'Bamberg','1736');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (232,'Seevetal','59743');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (233,'Anchorage','68268-316');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (234,'Orilla','56074');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (235,'Blenheim','4867');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (236,'Brussel','4757');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (237,'Macclesfield','E7R 4RI');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (238,'Kufstein','SV5 1TJ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (239,'Pike Creek','4251OE');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (240,'Bellefontaine','84523');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (241,'Sylvan Lake','6474');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (242,'Gap','4631NT');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (243,'Bicester','5851');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (244,'Waasmunster','14782-850');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (245,'San Giorgio Albanese','98007');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (246,'Lorient','RA4 4NB');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (247,'San Valentino in Abruzzo Citeriore','4506');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (248,'Sivry','3811');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (249,'Lint','15501');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (250,'Nanaimo','1913');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (251,'College','Q4C 0QI');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (252,'Linkebeek','7334');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (253,'Huelva','RY70 5NU');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (254,'Beausejour','6150');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (255,'Montereale','65537');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (256,'Laken','14268-290');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (257,'Norwich','2901');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (258,'Meeuwen-Gruitrode','9531');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (259,'Verrebroek','80010');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (260,'Polcenigo','7295');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (261,'Fontaine-l Eveque','2698');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (262,'Wernigerode','FI49 2CN');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (263,'Gosselies','27017');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (264,'Denver','50504');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (265,'Caccamo','35720-444');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (266,'Bungay','4058');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (267,'Mayerthorpe','25053');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (268,'Bad Vilbel','2207MB');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (269,'Altidona','8223');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (270,'Olinda','92850');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (271,'Miranda','6998OR');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (272,'Auvelais','83059');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (273,'Worcester','2319');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (274,'Moorsel','3672');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (275,'Montgomery','5122');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (276,'Tavistock','3309');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (277,'Thurso','11677');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (278,'Sauveniere','43774');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (279,'Bonefro','08896');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (280,'Marburg','28012');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (281,'Girona','74651-519');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (282,'Machelen','50110');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (283,'Cascavel','DH9 3JX');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (284,'Milestone','15435');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (285,'Minturno','1264ZG');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (286,'Campobasso','H7M 9Y7');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (287,'Lancaster','85914');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (288,'San Rafael','36255');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (289,'Lauro de Freitas','82327');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (290,'Pforzheim','61513');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (291,'Bingen','Y9R 6K8');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (292,'Auckland','7999');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (293,'Swan','7793');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (294,'Columbus','89283');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (295,'Juneau','P8M 3A7');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (296,'Cropalati','29986');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (297,'Campolieto','61827');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (298,'Grey County','1711');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (299,'Abingdon','7778');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (300,'Wilskerke','71406');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (301,'Yellowhead County','6801');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (302,'Oelegem','G7J 7V6');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (303,'Zweibrucken','99345');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (304,'San Pancrazio Salentino','6100');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (305,'Sherbrooke','4749');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (306,'Burlington','82384');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (307,'Vagli Sotto','C0E 8Y1');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (308,'Stony Plain','1649');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (309,'Groe-Gerau','14417');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (310,'Auvelais','25349');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (311,'Aalen','4277');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (312,'Delmenhorst','UI37 0FA');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (313,'Casacalenda','25446');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (314,'Marsciano','EO1 8HA');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (315,'Melilla','5542QG');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (316,'Benalla','9435');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (317,'Pau','67392');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (318,'Busso','1622ZX');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (319,'Carluke','50205');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (320,'Lachine','60609');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (321,'Aubagne','61910');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (322,'Zwickau','51071');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (323,'Messancy','32417');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (324,'Argyle','8141RZ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (325,'Ururi','T76 0EZ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (326,'St. Johns','50117');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (327,'Pollena Trocchia','X8K 0T8');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (328,'Schweinfurt','1945');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (329,'Vejano','9969');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (330,'Santa Cesarea Terme','60220');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (331,'Cetara','96574');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (332,'Collines-de-l Outaouais','8263');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (333,'Sint-Agatha-Berchem','2386YL');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (334,'Viano','79248');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (335,'Villa Verde','28439');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (336,'Broken Arrow','30643');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (337,'Cerreto di Spoleto','58035');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (338,'Champlain','5452');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (339,'Morhet','8223');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (340,'Klosterneuburg','HS2 6LR');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (341,'Montebello sul Sangro','A2B 6W2');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (342,'Juazeiro do Norte','47732');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (343,'Macquenoise','00321');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (344,'Rixensart','R8W 8V1');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (345,'Kufstein','5454');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (346,'Ravenstein','5970');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (347,'Cour-sur-Heure','74553');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (348,'La Baie','4491');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (349,'St. Albans','99014-284');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (350,'Slough','8603');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (351,'Stirling','0000');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (352,'Colico','4517');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (353,'Aurora','49527-485');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (354,'Great Falls','JF5 6RE');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (355,'Porirua','72700');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (356,'Idar-Oberstei','3118');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (357,'Pocatello','41637');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (358,'Lisciano Niccone','9917');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (359,'North Bay','31302');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (360,'Temse','52892');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (361,'Llanwrtwd Wells','H3Y 1N4');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (362,'Geertruidenberg','6625');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (363,'Massimino','6943');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (364,'Etalle','23257');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (365,'Koekelberg','83966');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (366,'Anklam','1441CB');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (367,'Lot','31023-587');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (368,'Swansea','00790-508');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (369,'Montgomery','67911');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (370,'Alness','G1 8CK');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (371,'Fermont','9447IP');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (372,'Nedlands','9767');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (373,'Colonnella','K6B 5J3');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (374,'Oostkamp','2313TZ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (375,'Gatineau','60920');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (376,'Harbour Grace','2596');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (377,'Santomenna','12996');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (378,'Cimolais','71808');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (379,'Lang','56328');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (380,'Pradamano','4248PF');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (381,'Weelde','L2V 1N8');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (382,'Waver','4404MQ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (383,'Wolfsberg','E6E 2H4');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (384,'Balfour','57309-481');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (385,'Goulburn','40880');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (386,'Oromocto','74995');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (387,'Booischot','7055');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (388,'Ottawa-Carleton','14498');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (389,'Sant Angelo a Fasanella','1832');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (390,'Nijkerk','27426');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (391,'Jonquiere','81192');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (392,'Eisleben','4859');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (393,'Great Falls','RB65 0DE');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (394,'Baracaldo','58179');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (395,'Maizeret','75368-436');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (396,'Port Alice','49902');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (397,'Kufstein','L0A 8W3');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (398,'Crato','1073');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (399,'Sint-Amandsberg','7387');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (400,'Yeovil','3383IR');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (401,'Castelseprio','1803');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (402,'Roccasicura','54795');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (403,'Esterzili','0415KK');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (404,'Colchester','T1Z 2E2');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (405,'Rebecq','46689');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (406,'Oostende','65163');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (407,'Villamassargia','70015');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (408,'Palmerston North','61802');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (409,'Alkmaar','25399');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (410,'Selkirk','51819');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (411,'St. Davids','49565');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (412,'Port Pirie','6550');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (413,'Russell','9781');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (414,'Sacramento','N80 2TJ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (415,'Cavasso Nuovo','1831');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (416,'Erie','J5A 5E8');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (417,'Buzenol','7991');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (418,'Bevilacqua','2951');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (419,'Manchester','Y7W 7P1');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (420,'Lingen','26189');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (421,'Topeka','7034');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (422,'Hay River','7342');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (423,'Valbrevenna','10193');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (424,'Stalhille','34480');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (425,'Silverton','16121');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (426,'Plauen','69256');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (427,'Moorsele','5408');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (428,'Saint-Georges','42282-078');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (429,'Burnaby','55402');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (430,'Recanati','78930');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (431,'Elversele','9840');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (432,'Ludwigsfelde','6001');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (433,'Carleton','49472');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (434,'Venezia','5781OK');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (435,'Boise','K6A 3K3');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (436,'Sant Agata Bolognese','45374');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (437,'Thiaumont','20400');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (438,'Namur','Y2V 5S5');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (439,'Freising','3560');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (440,'Caldarola','74859');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (441,'Kansas City','9381');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (442,'Giarratana','57089');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (443,'Colchester','24724');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (444,'Zolder','N6C 9G3');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (445,'Oordegem','2279TK');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (446,'Kleinmachnow','J0R 7S2');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (447,'Stekene','99731');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (448,'Troon','2578EV');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (449,'Newbury','72068');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (450,'St. Catharines','53283');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (451,'Londerzeel','80275');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (452,'Heestert','1830');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (453,'Pointe-du-Lac','46213-946');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (454,'Airdrie','2887');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (455,'Aurillac','93156');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (456,'West Ham','36500');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (457,'Merignac','59580');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (458,'Marchienne-au-Pont','6902');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (459,'Oostmalle','8889');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (460,'Machynlleth','42255');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (461,'Richmond','4811');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (462,'Seevetal','26603');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (463,'Temse','C5G 2H4');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (464,'Ekeren','5774');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (465,'Shadiac','1025ND');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (466,'Valcourt','71917');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (467,'Vancouver','4256');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (468,'Philadelphia','50443');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (469,'Bomal','Y66 3SJ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (470,'Venlo','82162');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (471,'Campochiaro','3385');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (472,'Canmore','60744');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (473,'Reutlingen','11467');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (474,'Whitewater Region Township','70843');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (475,'Aalst','31301');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (476,'Villach','6917');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (477,'Morwell','25502');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (478,'Cumnock','8368');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (479,'Zandvoorde','45295-848');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (480,'Doel','35308');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (481,'Kirkland','91053');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (482,'Hull','59741');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (483,'Casalvieri','93046');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (484,'Prestatyn','71807');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (485,'Wolvertem','89277-020');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (486,'Benalla','S6Y 2C0');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (487,'Cantley','55944');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (488,'Boise','D55 2AT');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (489,'Allumiere','RN5 3GQ');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (490,'Matagami','28282');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (491,'Heron','45770');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (492,'Manoppello','71606');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (493,'Isnes','6927');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (494,'Rhyl','5137');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (495,'Cotee-Saint-Luc','29131');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (496,'Asigliano Veneto','3048');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (497,'North Vancouver','N2H 6S2');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (498,'Chesterfield','26514-674');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (499,'Thurso','35149');
INSERT INTO `town` (`id`,`name`,`postcode`) VALUES (500,'Tullibody','F3T 8JI');
